blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("post/<int:pk>/", views.detail, name="detail"),
    path("archives/<int:year>/<int:month>/", views.archives, name="archives"),
    path("category/<int:pk>/", views.category, name="category"),
    path("tag/<int:pk>/", views.tag, name="tag"),

]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

hellodjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path('', include('comments.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


class Category(models.Model):
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    objects = models.Manager()
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    objects = models.Manager()
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    objects = models.Manager()
    title = models.CharField("标题", max_length=70)
    body = models.TextField("正文")
    created_time = models.DateTimeField("创建时间", default=timezone.now)
    modified_time = models.DateTimeField("修改时间")
    excerpt = models.CharField("摘要", max_length=200, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name="标签",  blank=True)
    category = models.ForeignKey(
        Category, verbose_name="分类",  on_delete=models.CASCADE)
    author = models.ForeignKey(
        User, verbose_name="作者", on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()

        # 首先实例化一个 Markdown 类，用于渲染 body 的文本。
        # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
        md = markdown.Markdown(extensions=[
            # extra 本身包含很多基础拓展，而 codehilite 是语法高亮拓展，
            # 这为后面的实现代码高亮功能提供基础，而 toc 则允许自动生成目录
            "markdown.extensions.extra", "markdown.extensions.codehilite",
        ])
        # 先将 Markdown 文本渲染成 HTML 文本
        # strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 从文本摘取前 54 个字符赋给 excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)
    """
第二种方法是使用 truncatechars 模板过滤器（Filter）。在 django 的模板系统中，模板过滤器的使用语法为 {{ var | filter: arg }}。
可以将模板过滤看做一个函数，它会作用于被它过滤的模板变量，从而改变模板变量的值。例如这里的 truncatechars 过滤器可以截取模板变量值
的前 N 个字符显示。关于模板过滤器，我们之前使用过 safe 过滤器，例如摘要效果，需要显示 post.body 的前 54 的字符，
那么可以在模板中使用 {{ post.body | truncatechars:54 }}。
例：<div class="entry-content clearfix">
      <p>{{ post.body|truncatechars:54 }}</p>
      <div class="read-more cl-effect-14">
          <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
      </div>
  </div>
不过这种方法的一个缺点就是如果前 54 个字符含有块级 HTML 元素标签的话（比如一段代码块），会使摘要比较难看(无法去除HTML的标签，
在第一种方法中，使用strip_tags函数可以去除标签）。所以推荐使用第一种方法。
    """

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})

    def __str__(self):

        return self.title
# Create your models here.

comments/models.py
from django.db import models
from django.utils import timezone


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey(
        'blog.post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论区'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:26])


# Create your models here.

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
import re
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
import markdown

# 首页文章列表视图


def index(request):
    post_list = Post.objects.all()
    return render(request, "blog/index.html", context={
        # "title": "钊华的601小屋首页",
        # "welcome": "欢迎访问我的小屋首页",
        "post_list": post_list
    })


# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     post.body = markdown.markdown(post.body, extensions=[
#         # extra 本身包含很多基础拓展，而 codehilite 是语法高亮拓展，
#         # 这为后面的实现代码高亮功能提供基础，而 toc 则允许自动生成目录
#         "markdown.extensions.extra", "markdown.extensions.codehilite", "markdown.extensions.toc"
#     ])

#     return render(request, "blog/detail.html", context={
#         # "title": "钊华的601小屋首页",
#         # "welcome": "欢迎访问我的小屋首页",
#         "post": post
#     })

# 点击进入文章后文章详细视图
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 记得在顶部引入 TocExtension 和 slugify
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    # print(post.body)
    # 这里可以上百度多查查用法
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''
    return render(request, 'blog/detail.html', context={'post': post})

# 点击边栏时间后，进入当前时间下所属文章页面列表


def archives(request, year, month):
    post_list = Post.objects.filter(
        created_time__year=year, created_time__month=month)
    return render(request, "blog/index.html", context={
        "post_list": post_list
    })

# 点击边栏文章分类后，进入当前分类下所属文章页面列表


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, "blog/index.html", context={
        "post_list": post_list
    })

# 点击边栏文章标签后，进入当前标签下所属文章页面列表


def tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=tag)
    return render(request, "blog/index.html", context={
        "post_list": post_list
    })
# Create your views here.
# print(__name__)

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post
from django.views.decorators.http import require_POST
from .forms import CommentForm
from django.contrib import messages


@require_POST
def comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)

    # django 将用户提交的数据封装在 request.POST 中，这是一个类字典对象。
    # 我们利用这些数据构造了 CommentForm 的实例，这样就生成了一个绑定了用户提交数据的表单。
    form = CommentForm(request.POST)

    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid():
        # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)
        # 将评论和被评论的文章关联起来。
        comment.post = post
        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        comment.save()

        # 发一条消息回来告诉用户，评论成功，已经存入数据库.
        messages.add_message(request, messages.SUCCESS,
                             '评论发表成功，又一个小可爱看到了我的网站！', extra_tags='success')
        return redirect(post)

    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址。
    context = {
        'post': post,
        'form': form,
    }
    # 发一条消息回来告诉用户，评论失败，重新填写.
    messages.add_message(request, messages.ERROR,
                         '评论发表失败，我的小可爱看看是哪里没有填对哦-0-！', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

# Create your views here.

templates/base.html
{%load static%}
{% load blog_extras %}
<!DOCTYPE html>
<html>

<head>
    <title>钊华的601</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <a name="viewport" content="width=device-width, initial-scale=1">

        <!-- css -->
        <!-- <link rel="stylesheet" href="css/bootstrap.min.css"> -->
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- <link rel="stylesheet" href="css/pace.css">
    <link rel="stylesheet" href="css/custom.css"> -->
        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
        <link rel="stylesheet" href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css">
        <style>
            .codehilite {
                padding: 0;
            }

            /* for block of numbers */
            .hljs-ln-numbers {
                border-right: 1px solid #ccc;
                padding-right: 5px;

                text-align: center;
                vertical-align: top;

                color: #ccc;

                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;

                -webkit-touch-callout: none;
                -khtml-user-select: none;
            }

            .hljs-ln-n {
                width: 30px;
            }

            /* for block of code */
            .hljs-ln .hljs-ln-code {
                padding-left: 10px;

                white-space: pre;
            }
        </style>

        <!-- js -->
        <!-- <script src="js/jquery-2.1.3.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/pace.min.js"></script>
    <script src="js/modernizr.custom.js"></script> -->
        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{%url 'blog:index'%}"><b>钊华</b> &amp; 601小窝</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="index.html" data-hover="我">大一</a></li>
                                <li class="cl-effect-11"><a href="full-width.html" data-hover="love">大二</a></li>
                                <li class="cl-effect-11"><a href="about.html" data-hover="只">大三</a></li>
                                <li class="cl-effect-11"><a href="contact.html" data-hover="夏">大四</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="搜索" required>
                                <button type="submit"><span class="ion-ios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
        </header>
        <!-- 评论消息状态弹出框区域 -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss='alert' aria-label="close">
                <span aria-hidden="true">x</span>
            </button>
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
    <div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    {%block main%}

                    {%endblock main%}
                </main>
                <aside class="col-md-4">
                    {%block toc%}

                    {%endblock toc%}

                    <!-- <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最近随笔</h3>
                    <ul>
                        <li>
                            <a href="#">深圳四人组的椰子鸡游记</a>
                        </li>
                        <li>
                            <a href="#">全哥的英国行</a>
                        </li>
                        <li>
                            <a href="#">微信的@官方大赛</a>
                        </li>
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        <li>
                            <a href="#">2019 年 9 月</a>
                        </li>
                        <li>
                            <a href="#">2019 年 8 月</a>
                        </li>
                        <li>
                            <a href="#">2019 年 7 月</a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        <li>
                            <a href="#">钊华自己的心事 <span class="post-count">(13)</span></a>
                        </li>
                        <li>
                            <a href="#">最近的沙雕图 <span class="post-count">(11)</span></a>
                        </li>
                        <li>
                            <a href="#">大和的皇居爆炸日记 <span class="post-count">(8)</span></a>
                        </li>
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        <li>
                            <a href="#">Django</a>
                        </li>
                        <li>
                            <a href="#">Python</a>
                        </li>
                        <li>
                            <a href="#">Java</a>
                        </li>
                        <li>
                            <a href="#">笔记</a>
                        </li>
                        <li>
                            <a href="#">文档</a>
                        </li>
                        <li>
                            <a href="#">AngularJS</a>
                        </li>
                        <li>
                            <a href="#">CSS</a>
                        </li>
                        <li>
                            <a href="#">JavaScript</a>
                        </li>
                        <li>
                            <a href="#">Snippet</a>
                        </li>
                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div> -->
                    {% show_recent_posts %}
                    {% show_archives %}
                    {% show_categories %}
                    {% show_tags %}
                    <div class="rss">
                        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2019-10 - 采集自<a href="http://www.cssmoban.com/" target="_blank"
                            title="模板之家">模板之家</a>
                        - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">15生医梁钊华</a>修改
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{%url 'blog:index'%}">首页</a></li>
                <li><a href="full-width.html">博客</a></li>
                <li><a href="about.html">关于</a></li>
                <li><a href="contact.html">联系</a></li>
            </ul>
        </nav>
    </div>

    <!-- <script src="js/script.js"></script> -->
    <script src="{% static 'blog/js/script.js' %}"></script>
    <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
    <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
    <script>
        hljs.initHighlightingOnLoad();
        hljs.initLineNumbersOnLoad();
    </script>
</body>

</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load comment_extras %}
{%block main%}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a
                    href="{%url 'blog:category' post.category.pk%}">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                        datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#comment-area">{{post.comment_set.count}} 评论</a></span>
            <span class="views-count"><a href="{{ post.get_absolute_url }}">588 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <!-- <blockquote> -->
        {{ post.body | safe }}
        <!-- </blockquote> -->
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <!-- 静态表单的html编写 -->
    <!-- <form action="#" method="post" class="comment-form">
        <div class="row">
            <div class="col-md-4">
                <label for="id_name">名字：</label>
                <input type="text" id="id_name" name="name" required />
            </div>
            <div class="col-md-4">
                <label for="id_email">邮箱：</label>
                <input type="email" id="id_email" name="email" required />
            </div>
            <div class="col-md-4">
                <label for="id_url">网址：</label>
                <input type="text" id="id_url" name="url" />
            </div>
            <div class="col-md-12">
                <label for="id_comment">评论：</label>
                <textarea name="comment" id="id_comment" required></textarea>
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>
    </form>  -->
    {% show_comment_form post %}

    <div class="comment-list-panel">
        <!-- <h3>评论列表，共 <span>4</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            <li class="comment-item">
                <span class="nickname">追梦人物</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月12日 14:56</time>
                <div class="text">
                    文章观点又有道理又符合人性，这才是真正为了表达观点而写，不是为了迎合某某知名人士粉丝而写。我觉得如果琼瑶是前妻，生了三孩子后被一不知名的女人挖了墙角，我不信谁会说那个女人是追求真爱，说同情琼瑶骂小三的女人都是弱者。
                </div>
            </li>
            <li class="comment-item">
                <span class="nickname">zmrenwu</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月11日 23:56</time>
                <div class="text">
                    本能有可能会冲破格局，但格局有时候也会拘住本能。
                </div>
            </li>
            <li class="comment-item">
                <span class="nickname">蝙蝠侠</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年3月9日 8:56</time>
                <div class="text">
                    其实真理一般是属于沉默的大多数的。那些偏激的观点只能吸引那些同样偏激的人。前几年琼瑶告于妈抄袭，大家都表示大快人心，说明吃瓜观众都只是就事论事，并不是对琼瑶有偏见。
                </div>
            </li>
            <li class="comment-item">
                <span class="nickname">长江七号</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">2017年2月12日 12:56</time>
                <div class="text">
                    观点我很喜欢！就是哎嘛本来一清二楚的，来个小三小四乱七八糟一团乱麻夹缠不清，简直麻烦要死
                </div>
            </li>
        </ul> -->
        {%show_comments post%}
    </div>
</section>
{%endblock main%} {%block toc%}
<!-- <div class="widget widget-content">
	<h3 class="widget-title">文章目录</h3>
	<ul>
		<li>
			<a href="#">教程特点</a>
		</li>
		<li>
			<a href="#">谁适合这个教程</a>
		</li>
		<li>
			<a href="#">在线预览</a>
		</li>
		<li>
			<a href="#">资源列表</a>
		</li>
		<li>
			<a href="#">获取帮助</a>
		</li>
	</ul>
</div> -->
{% if post.toc %}
<div class="widget widget-content">
    <h3 class="widget-title"> 文章目录</h3>
    <div class="toc">
        <ul> {{ post.toc | safe}} </ul>
    </div>
</div>
{% endif %} {%endblock toc%}

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
        <li>
            <!-- 这里  url 这个模板标签的作用是解析视图函数 blog:archive 对应的 URL 模式，
                并把 URL 模式中的年和月替换成 date.year，date.month 的值。 -->
            <a href="{%url 'blog:archives' date.year date.month%}">
                {{ date.year }} 年 {{ date.month }} 月</a>
        </li>
        {% empty %} 暂无归档！ {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
        <li>
            <a href="{%url 'blog:category' category.pk%}">
                {{ category.name }} <span class="post-count">(13)</span>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
	<h3 class="widget-title">最新文章</h3>
	<ul>
		{% for post in recent_post_list %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
		{% empty %} 暂无文章！ {% endfor %}
	</ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {% for tag in tag_list %}
        <li>
            <a href="{%url 'blog:tag' tag.pk%}">{{ tag.name }}</a>
        </li>
        {% empty %} 暂无标签！ {% endfor %}
    </ul>
</div>

templates/blog/index.html
{% extends 'base.html' %} {%block main%}
{% for post in post_list %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a
                    href="{%url 'blog:category' post.category.pk%}">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                        datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{post.comment_set.count}}
                    评论</a></span>
            <span class="views-count"><a href="{{ post.get_absolute_url }}">588 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ post.excerpt }}</p>
        <div class="read-more cl-effect-14">
            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
</article>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}
<!-- 简单分页效果 -->
<!-- <div class="pagination-simple">
	<a href="#">上一页</a>
	<span class="current">第 6 页 / 共 11 页</span>
	<a href="#">下一页</a>
</div> -->

<div class="pagination">
    <ul>
        <li><a href="">1</a></li>
        <li><a href="">...</a></li>
        <li><a href="">4</a></li>
        <li><a href="">5</a></li>
        <li class="current"><a href="">6</a></li>
        <li><a href="">7</a></li>
        <li><a href="">8</a></li>
        <li><a href="">...</a></li>
        <li><a href="">11</a></li>
    </ul>
</div>
{%endblock main%}

templates/comments/inclusions/_form.html
<form action="{%url 'comments:comment' post.pk%}" method="post" class="comment-form">
    {%csrf_token%}
    <div class="row">
        <div class="col-md-4">
            <label for="{{form.name.id_for_label}}">{{form.name.label}}:</label>
            {{form.name}}
            {{form.name.errors}}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
        </div>
    </div>
    <!-- row -->
</form>

templates/comments/inclusions/_list.html
<h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
    <li class="comment-item">
        <span class="nickname">{{ comment.name }}</span>
        <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
        <div class="text">
            {{ comment.text|linebreaks }}
        </div>
    </li>
    {% empty %}
    暂无评论
    {% endfor %}
</ul>
<!-- 要注意这里 {{ comment.text|linebreaks }} 中对评论内容使用的过滤器 linebreaks，
    浏览器会将换行以及连续的多个空格合并为一个空格。如果用户评论的内容中有换行，浏览器
    会将换行替换为空格，从而显示的用户评论内容就会挤成一堆。linebreaks 过滤器预先将换
    行符替换为 br HTML 标签，这样内容就能换行显示了。 -->

templates/comments/preview.html
{%extends 'base.html'%}
{%load comment_extras%}

{%block main%}
{%show_comment_form post form %}
{%endblock main%}